# Generated by Django 2.2.7 on 2019-12-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yahtzee_app', '0002_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='waiting_for_game',
            field=models.BooleanField(null=True),
        ),
    ]
