# Generated by Django 2.2.7 on 2019-12-20 04:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yahtzee_app', '0004_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='game_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
